// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbb28bN9L/KgT7AM8dsJLsNgccBPSF4yS1UCcx7CR90QQBtRxpWXPJLTkrW1foux9I",
	"7korLXclp3baXvWqiknO/xn+Zrj9jaY6L7QChZaOf6M2zSBn/ufZHBS6H4XRBRgU4P+cGmAI/MwvzbTJ",
	"GdIx5QxhgCIHmlBcFkDH1KIRak5XiTvCQaFg8r2R7lhrh+Bb1MpS8BghiwxLLwWoMqfjn6nSOEi1UpAi",
	"uCN3TKBQ88FMm8GGraUJBWO0oQmdM8zAERwIJdziQKgFKNRmSRNaFgPUA6cNTajVpUlhMNcK6KdOcSZq",
	"pqNKlQV/qKUWYKzQKkJulVADv5bCAHd6e/tU5tgSZNfaScNhTZE2vDaa6ekvkKKTw/v+yuj7ZTsAMsSi",
	"8mMu1CWoOWZ0fJpQVUrJphLoGE0Ju9ol9H6gWSEGqeYwBzWAezRsgGzuqS6YFN7sY6pzgUrIpDQyscgM",
	"WqXxTmD2vWNtvS38r68sxY4ISq8N9LQS5Oz++9OTkxO6cmxbvnrBkFnUBtqu4sLeTng0OGcG4JwVLBW4",
	"/OF5Y4tQCHMwbk/GDL9jBs7SFCQYFzmv9QIam6daS2DKbc41h3hyF0ajTrV85xciG1Ajk/uEwa7TC1Bc",
	"m/0p41fbzFqmWFNMavt1W2JHudoKsZR66etPy0U5WMvmXjMONjWiQF8Awn5SLyd7lKv3fVol9EJY1HPD",
	"8khAMGTuvwIht312pswYtvR+FeoDkyXEd1uEIrayK15NpDqRBElidrrQNnLrdEfXoe5fO7XbRRM1Myxy",
	"48nSIhh7BcblWgoKwTzQirxOUrt18P8MzOiYfjPa3MKj6goebfI6Qi/TFq/0HZgbZBiIMs6Fix0mr7bE",
	"7xRuo7ijdrhg3kMdMjkjnQd7PdBCCvBOm9vDxXgTDsRohRyv3NbB3m3ZuLNv10VtnT1B3ti8K0LbOG0X",
	"NkywFS/xSK0hSytaRR3EfbYLke6yZxPNffs/nIdt7sR+z3x4bdvpVzEKBJJKzJhul2waUn1br1tYtpP8",
	"8Mu0liWRnrwTb7FT1n4/zR2dncg1m5imr8XcMJeyE2vLyPXNrAVr8wqGt2G1LrdWGnEr4pe+rE3bXyrD",
	"tqTJv+a2X43DE3hH/Uge1ynevscWDo2lWVRLxfIOnFFBiLp5sMgUZ4aHmx6NmJahi1iTT2ipbFkU2riF",
	"WA+wkExFIVYcfXjZYka88b1GJAbqLqzPkqFVWyVf0pwd2HqJZsXpLy31xjrgDo+IkPqxy6HLpVpdGciF",
	"3brqGqj0wT1YrM/y3LsbqYYM3Z4994cj4ML9nImUIZxnTKi9tbUqP/x89+BjmfthDQrkBS4TLhaQrO22",
	"anjsIF2Cid64I6FfuF8eFPKhAXMw1GZX5VSK9EdYHs715mJzaNfxexL1UgSUepCdq9yOxHVYeV/wY2x0",
	"6fK2CKD2TxIj7XhYz6S2+7fwdyIsYcQAlkYRjwTITBuSMiktwYwh4Vr9P9Y7NGZgSCBuh6G9PKRZPCNZ",
	"mTM1MMA4m0ogjWWiZwQzIGFIFP4lLHF0/e07jJV7A8yGOdQuo5ylmVDQyeouW+4wcDYQysvwkb5iQpYG",
	"PtJKniGZVAIF6whLfNi47cb/U2kiVCjdjhhbMOHHK0NyRq69mCSVzIiZAEuYIhfv3l3VyrowJdPSWRkc",
	"JSR6AcYIDkTgsH/EGHVnZcuN8chbBUTPxuQjvSnTFKz9SIk2TU2H5LV2qqiZHhM/PxqPRnOBw9t/26HQ",
	"Lv7yUglcjlKtAgrRxo44LECOrJgPmEkzgZBiaWAUss9fskIrO8z5N7aAdMAUH6wHgu1LrRW3oej0NBIe",
	"eUyeDh3s3rSNKWzNOlZ/61ak3fjwg8amUZqvryEMe58bYLdc36nI3LM5Vuntj9cb6w6yp7l8pU3AwWFi",
	"eNi+nwRmPzGjhJrb/jNvNPaT3zHQRsla9Kice4XqkiBufRu5+4ryvB6X9PeabdetwuTuvO6PvvB8mER+",
	"weG8bmyaPnqklkiJ9PfopZreCNXzMaXTD5xEcSgMOJjCd4blm+jQ6weWLrJ9IlenYwWweLTxmWH5F8fK",
	"vvpwUHE4vDLERla0zSrZ5F+t3jonmsnlPb5tyo4Yi2VFtBh0Ytgnf2dxcDsMrvrA5++YF20wcQiEzw4I",
	"J7lQ35/Wjzzb7LfQ55Prb232+baCubHW7DEmZf2Kb3J95zLonnRtpjOR/n8n2tMqZmMTnUZdMGDFXAEf",
	"lCYyh4T7QhiwnxlG3mzcWoCpKPIA9R1cfH99SVDfgsfah41lKt7b9K8MDIJsnqQj7+qI1IwLNQ8o3xuY",
	"cGFTB3WXRORsDsO9gw7Hr22Nlcd2wSVSpKCsD4PQwNGzgqUZkG+HJ7QSmNbw9u7ubsj88lCb+ag6a0eX",
	"k/OXb25eDr4dngwzzEOHKdAF8WaOSK4kUwoMObuaNB6qx7RUHGZCuTYyoboAxQpBx/S74cnw1JUhhpn3",
	"kQPJo8XpKBijQvMSMNI5hb8TRlItJaR1F1Of9GyqS4/TMX3ht9+sVw3YQqtq/PTtyUmIVoXV0I4VhXQl",
	"TGg1+qVqqMKFsHdmEKC898C2xG9/dNo/Ozl9NF7haTLC6r1iJWbaiP8Ek//rERXsZDpx8F4xSaDakdBQ",
	"UX6uPsjwj5xziOTfpbDY6Tq3uHFcwQzLIbz8/LxLx/dhWpK7jCEsICQxhxkrpWvVXfEgNtOl5GQKhHEO",
	"nKD2uwzYUqJ/4KBj+msJvqGpEkaoVJYcPlekXCla26pVuz49ZXRthljHCOuIsKJ6iN4+G+a4hFVh1oqy",
	"sH5TL7oSCxafa758ZOdVA+WdRyeHBFatwDl9ZN4xowZ5eIicr+DE54yT62DdY7Sukt07b/Sb4Ku+i+9F",
	"ffF1BHLzpttXLycv1kPGer8vf+5CblQ/TndDtVkA9wyZvkI97KuFf5OIfnby3dMzfaXNVHAOKnB89vQc",
	"32h8pUv19ZJ2w/AB8OUHwJBEBaRiJoB35eYPgMfEPCbmMTGfDPuVkfQMLyZdORlW/2xp+VTos3qyPgh9",
	"fo1qEORZF8xjZThWhi+uDDdgXM//8sFwe+Rnbf6tEBhvF5ALYNxn/dsPZ2Eu16oibsukWukvIfyPu9l7",
	"LuJD0uOgcN4ffnvD5aHuDR7Z4916KNwL4Nb+JQvByPvry24E96Ka34ZNvS4PB4j31F8LxW2P1GM1zQ/I",
	"18PsRoL8vSr5sz+oM9kb+lufifSAo+ZXHDF8NGms/89CpF1V/6QoqeGsI1464qU/AC+ZBWodPkrtKyr1",
	"jJJMl6Qs6tdOpsj1h3fuPJkJCYQLAynKWOVxR64Dr1dC/gXas7yUKApmcOTIDOr/bW9DfftN2unftt67",
	"DLYt9I+X9ynIfzbfoKdCMV+M+1+HPYP48/Dj1rXO7133ftEYyUGnc4gXV/PC15mzUspjvTvWuyevdxkw",
	"iVlnqxCWSZpBehvrAqUvNYd1Xw0RKq6fvPzWCxoqXPg8Y0RXn1b/DQAA//8enYZs9EEAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
